name: crisptv
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router:
  url_strategy: ^0.2.0
  number_paginator: ^0.2.3
  share_plus: ^7.0.0
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+3
  path_provider: ^2.0.11
  flutter_quill: ^9.2.6
  #flutter_quill: ^6.4.4
  url_launcher: ^6.1.7
  #flutter_quill_extensions: ^0.1.0
  flutter_widget_from_html: ^0.9.0+1
  firebase_core: ^2.13.1
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  delta_to_html: ^0.2.2
  youtube_player_iframe: ^4.0.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf
 
 
